import Header from "@/components/layout/header/Header";
import "./globals.css";
import Footer from "@/components/layout/footer/Footer";
import { QuickViewProvider } from "@/context/ContextProvider";
import QuickView from "@/components/common/QuickView";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <QuickViewProvider>
          <QuickView />
          <Header />
          {children}
          <Footer />
          
        </QuickViewProvider>
        
      </body>
    </html>
  );
}
